window._CCSettings = {
    platform: "web-mobile",
    groupList: [
        "default",
        "sodButtom",
        "topOurItem",
        "topOtherItem",
        "topOurBase",
        "topOtherBase",
        "boundary",
        "control",
        "gameMap",
        "DW_Map"
    ],
    collisionMatrix: [
        [
            true
        ],
        [
            false,
            true
        ],
        [
            false,
            false,
            true,
            true,
            null,
            true,
            true
        ],
        [
            false,
            false,
            true,
            true,
            true,
            null,
            true
        ],
        [
            false,
            false,
            false,
            true,
            false
        ],
        [
            false,
            false,
            true,
            false,
            false,
            false
        ],
        [
            false,
            false,
            true,
            true,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ]
    ],
    hasResourcesBundle: false,
    hasStartSceneBundle: false,
    remoteBundles: [],
    subpackages: [],
    launchScene: "db://assets/main/loading.fire",
    orientation: "portrait",
    debug: true,
    jsList: [],
    bundleVers: {
        internal: "cb4f5",
        BACK_Audio: "0cf8b",
        BACK_Config: "d6c29",
        BACK_Prefabs: "e1dda",
        BACK_SpAnim: "288b6",
        BACK_Sprite: "2280a",
        BHD_Audio: "3040c",
        BHD_Config: "5e9ef",
        BHD_Prefabs: "66095",
        BHD_SpAnim: "308e1",
        BHD_Sprite: "4f23d",
        BKT_Audio: "00b8d",
        BKT_Config: "e1ebc",
        BKT_Prefabs: "97da3",
        BKT_SpAnim: "7af3e",
        BKT_Sprite: "dd287",
        BraveTowerAudio: "059dd",
        BraveTowerConfig: "9196c",
        BraveTowerConfigB: "9ab86",
        BraveTowerConfigD: "65209",
        BraveTowerEffect: "5dc8a",
        BraveTowerEnemy: "a4ef7",
        BraveTowerGameCard: "9dec4",
        BraveTowerIcon: "d95a5",
        BraveTowerIconBuff: "9b899",
        BraveTowerIconCard: "47e9f",
        BraveTowerIconHead: "2ff05",
        BraveTowerIconSkill: "373fa",
        BraveTowerIconTies: "c4e51",
        BraveTowerMap: "1be12",
        BraveTowerPrefab: "1aef6",
        DBS_Audio: "036b3",
        DBS_Config: "39433",
        DBS_Prefabs: "70dfb",
        DBS_SpAnim: "247c5",
        DBS_Sprite: "c0ecd",
        DW_Audio: "1ef9d",
        DW_Config: "f83af",
        DW_Prefabs: "965b8",
        DW_SpAnim: "ceab9",
        DW_Sprite: "9a601",
        FSL_Audio: "2dbb1",
        FSL_Config: "2aeae",
        FSL_Prefabs: "42764",
        FSL_SpAnim: "41f56",
        FSL_Sprite: "e4003",
        RCPDD_Audio: "b93e4",
        RCPDD_Config: "142de",
        RCPDD_Prefabs: "f7f85",
        RCPDD_SpAnim: "a1135",
        RCPDD_Sprite: "2d495",
        TLB_Audio: "d57f4",
        TLB_Config: "3b1a9",
        TLB_Prefabs: "c2741",
        TLB_SpAnim: "c9f6b",
        TLB_Sprite: "eec0c",
        TPVP_Audio: "8568b",
        TPVP_Config: "c9c5f",
        TPVP_Prefabs: "5d9c9",
        TPVP_SpAnim: "46563",
        TPVP_Sprite: "f3ad3",
        ball_audios: "afe3b",
        ball_configs: "e2d30",
        ball_configsB: "be383",
        ball_imgs: "ae502",
        ball_prefabs: "13443",
        bty_audios: "b926c",
        bty_configs: "ce967",
        bty_imgs: "7bf7b",
        bty_prefabs: "a584b",
        configPrivacy: "801b0",
        db_audios: "a1aca",
        db_configs: "a11ab",
        db_imgs: "51189",
        db_prefabs: "ea39f",
        dmd_audios: "5b3e7",
        dmd_configs: "1c97f",
        dmd_gameIcon: "3a34d",
        dmd_prefabs: "cd785",
        dra_audios: "49518",
        dra_configs: "48911",
        dra_configsB: "f191f",
        dra_imgs: "42fa2",
        dra_prefabs: "bdb96",
        gad_audios: "c4057",
        gad_configs: "299d0",
        gad_imgs: "3e749",
        gad_prefabs: "4f66b",
        hold_audios: "0af5d",
        hold_configs: "b8337",
        hold_prefabs: "1bc06",
        pbt_audios: "fcdc3",
        pbt_configs: "ddb73",
        pbt_imgs: "c8722",
        pbt_prefabs: "78e16",
        run_audios: "e1b75",
        run_configs: "5cfe0",
        run_imgs: "a82a0",
        run_prefabs: "364ab",
        sod_audios: "a62f7",
        sod_configs: "0f1a4",
        sod_prefabs: "d5a71",
        sto_audios: "81d78",
        sto_configs: "f5344",
        sto_imgs: "213f5",
        sto_prefabs: "95a3e",
        main: "27e32"
    }
};
